Fix error messages when a benchmark isn't found.
Previously this led to the following being printed:

  ERROR: instance of Vector

which was a bit confusing. With this commit it prints:

  ERROR: Failed loading benchmark: Richards

I found this while getting class paths wrong!